[package]
name = "tuicord"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
ratatui = "0.29.0"
reqwest = { version = "0.12.12", features = ["json"] }
tokio = { version = "1.43.0", features = ["full"] }
