[package]
name = "tuicord"
version = "0.1.0"
edition = "2021"

[dependencies]
open = "5.3.2"
ratatui = "0.29.0"
reqwest = "0.12.12"
serenity = "0.12.4"
tokio = { version = "1.43.0", features = ["full"] }
